repos:
  ######
  #
  # Standard hooks for any repo
  #
  #####
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: .+\.csv$
      # Useful if you want to enforce feature branches beginning with a Jira ticket ID
      # - id: no-commit-to-branch
      #   name: JIRA ticket ID in branch
      #   args: ['--pattern', '^((?![A-Z]+[-][0-9]+[-][\S]+).)*$']

  ######
  #
  # Hooks for python files
  #
  #####
  - repo: local
    hooks:
      - id: isort
        entry: python -m isort --profile black --filter-files
        language: system
        name: isort
        pass_filenames: true
  - repo: local
    hooks:
      - id: black
        entry: python -m black
        language: system
        name: Run black formatter
        pass_filenames: true
        types_or: [python, pyi]
  - repo: local
    hooks:
      - id: autoflake
        entry: python -m autoflake --in-place --remove-all-unused-imports
        language: system
        name: Run autoflake
        pass_filenames: true
        types_or: [python, pyi]
  - repo: local
    hooks:
      - id: pyupgrade
        entry: python -m pyupgrade
        language: system
        name: Check for code that can use new Python features
        pass_filenames: true
        types_or: [python, pyi]

  ######
  #
  # Hooks for dbt projects
  #
  #####
  - repo: local
    hooks:
      - id: sqlfmt
        entry: python -m sqlfmt
        language: system
        name: Run sqlfmt
        pass_filenames: true
        types_or: [jinja, sql]

  ######
  #
  # Custom hooks for dbt projects
  #
  #####
  - repo: local
    hooks:
      - id: pytest-no-deps
        name: pytest-no-deps
        entry: pytest ./tests/pytest -m no_deps -n 5
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: pytest-catalog-json
        name: pytest-catalog-json
        entry: pytest ./tests/pytest -m catalog_json -n 5
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: pytest-manifest-json
        name: pytest-manifest-json
        entry: pytest ./tests/pytest -m manifest_json -n 5
        language: system
        pass_filenames: false
        always_run: true
