name: 'beyond_basics'
version: '1.0.0'
config-version: 2

profile: 'beyond_basics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.11.0", "<1.12.0"]

models:
  +labels:
    created_by: dbt
  beyond_basics:
    +persist_docs:
      relation: true
      columns: true
    intermediate:
      finance:
        +schema: intermediate_finance
        +tags: ['finance']
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate']
    marts:
      crypto:
        +schema: marts_crypto
        +tags: ['crypto']
      finance:
        +schema: marts_finance
        +tags: ['finance']
      +materialized: table
      +schema: marts
      +tags: ['marts']
    staging:
      public_datasets:
        +schema: staging_public_datasets
        +tags: ['public_datasets']
      jaffle_shop:
        +schema: staging_jaffle_shop
        +tags: ['jaffle_shop']
      stripe:
        +schema: staging_stripe
        +tags: ['stripe']
      +materialized: view
      +schema: staging
      +tags: ['staging']


seeds:
  beyond_basics:
    jaffle_shop:
      +schema: seeds_jaffle_shop
      +tags: ['jaffle_shop']
    stripe:
      +schema: seeds_stripe
      +tags: ['stripe']
    +tags: ["seeds"]
flags:
  require_generic_test_arguments_property: true
