[project]
name = "dbt-beyond-the-basics"
version = "0.0.0"
description = "Showcase of advanced use cases relating to CI in dbt"
readme = "README.md"
authors = [{name="Padraic Slattery",email="pgoslatara@gmail.com"}]
maintainers = [{name="Padraic Slattery",email="pgoslatara@gmail.com"}]
license = {text = "MIT"}
keywords = [
  "python",
  "sql",
  "Continuous Integration",
  "dbt",
]
requires-python = ">=3.11,<3.12"
dependencies = [
    "dbt-core>=1.11.0,<1.13.0",
    "dbt-bigquery>=1.11.0,<1.13.0",
]

[project.urls]
Repository = "https://github.com/pgoslatara/dbt-beyond-the-basics"

[dependency-groups]
dev = [
    "autoflake",
    "black",
    "dbt-artifacts-parser>=0.8",
    "dbt-bouncer>=3.0.2",
    "dbt-coverage",
    "dbterd",
    "duckdb",
    "flake8",
    "gitpython",
    "google-cloud-bigquery",
    "google-cloud-storage",
    "isort",
    "mermaid-py",
    "pre-commit",
    "pyarrow",
    "pytablewriter",
    "pytest",
    "pytest-xdist",
    "pyupgrade",
    "retry",
    "shandy-sqlfmt[jinjafmt]",
]

[tool.uv]
package = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 99
include = '/project$|\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.eggs
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vscode
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"

[tool.sqlfmt]
exclude=["target/**/*", "dbt_packages/**/*"]
