name: bigquery_cleanup

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

env:
  UV_VERSION: "0.9.24"

jobs:
  cleanup_stg:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7
        with:
          ref: stg

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Save stg GCP credentials to runner
        run: |
          echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_STG_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account dbt-cicd@beyond-basics-stg.iam.gserviceaccount.com --key-file=./service_account.json && \
          gcloud config set project beyond-basics-stg

      - name: Install python packages
        run: uv sync

      - run: uv run python ./scripts/drop_unused_bq_resources.py --dataset_pattern "cicd_" --environment stg

  cleanup_prd:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7
        with:
          ref: prd

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Save prd GCP credentials to runner
        run: |
          echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_PRD_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account dbt-cicd@beyond-basics-prd.iam.gserviceaccount.com --key-file=./service_account.json && \
          gcloud config set project beyond-basics-prd

      - name: Install python packages
        run: uv sync

      - run: uv run python ./scripts/drop_unused_bq_resources.py --dataset_pattern "cicd_" --environment prd
