name: Publish dbt docs

on:
  push:
    branches:
      - prd
  workflow_dispatch:

env:
    DBT_DATASET: "prd"
    DBT_PROFILES_DIR: "."
    UV_VERSION: "0.9.24"

jobs:
  publish-dbt-docs:
    name: Publish dbt Docs as GitHub Page
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v7

        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
            enable-cache: true
            version: ${{ env.UV_VERSION }}

        - name: Set up Python
          run: uv python install

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v3'

        - name: Save prd GCP credentials to runner
          run: |
            echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_PRD_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
            export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

        - name: Authenticate with GCP
          run: |
            gcloud auth activate-service-account dbt-cicd@beyond-basics-prd.iam.gserviceaccount.com --key-file=./service_account.json && \
            gcloud config set project beyond-basics-prd

        - name: Install python packages
          run: uv sync

        - name: Generate dbt docs
          run: |
            uv run dbt deps --target prd
            uv run dbt docs generate --target prd

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./target
