name: daily_runs

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      env_to_run:
        description: The environment in which to run the job
        default: 'stg'
        options:
          - prd
          - stg
        required: true
        type: choice

env:
  DBT_PROFILES_DIR: "."
  UV_VERSION: "0.9.24"

jobs:
  daily_run_stg:
    if: contains(fromJSON('["stg", ""]'), github.event.inputs.env_to_run)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
        with:
          ref: stg

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Save stg GCP credentials to runner
        run: |
          echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_STG_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account dbt-cicd@beyond-basics-stg.iam.gserviceaccount.com --key-file=./service_account.json && \
          gcloud config set project beyond-basics-stg

      - name: Install python packages
        run: uv sync

      - name: dbt dep
        run: uv run dbt deps

      - name: dbt seed
        run: uv run dbt seed --target stg
        env:
          DBT_DATASET: "stg"

      - name: dbt build
        run: uv run dbt build --exclude "test_type:unit" --target stg
        env:
          DBT_DATASET: "stg"

  daily_run_prd:
    if: contains(fromJSON('["prd", ""]'), github.event.inputs.env_to_run)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
        with:
          ref: prd

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Save prd GCP credentials to runner
        run: |
          echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_PRD_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account dbt-cicd@beyond-basics-prd.iam.gserviceaccount.com --key-file=./service_account.json && \
          gcloud config set project beyond-basics-prd

      - name: Install python packages
        run: uv sync

      - name: dbt dep
        run: uv run dbt deps

      - name: dbt seed
        run: uv run dbt seed --target prd
        env:
          DBT_DATASET: "prd"

      - name: dbt build
        run: uv run dbt build --exclude "test_type:unit" --target prd
        env:
          DBT_DATASET: "prd"
