name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  DBT_CICD_RUN: "true"
  DBT_DATASET: "ci_${{ github.event.number }}_${{ github.run_number }}_${{ github.sha }}"
  DBT_PROFILES_DIR: "."
  DESTINATION_BRANCH: "stg"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Save stg GCP credentials to runner
        run: |
          echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_STG_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

      - name: Install python packages
        run: pip install -r requirements.txt -r requirements_dev.txt

      - name: dbt docs generate
        run: dbt docs generate --target $DESTINATION_BRANCH

      - run: pre-commit autoupdate

      - name: pre-commit run -a
        run: SKIP=dbt-compile,dbt-docs-generate pre-commit run -a

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_GITHUB }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
          labels: automerge
