name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  DBT_DATASET: "stg"
  DBT_PROFILES_DIR: "."
  UV_VERSION: "0.9.24"

jobs:
  auto-update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install

      - name: Save stg GCP credentials to runner
        run: |
          echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_STG_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

      - name: Install python packages
        run: uv sync

      - name: dbt docs generate
        run: |
          uv run dbt deps
          uv run dbt docs generate --target stg

      - run: uv run pre-commit autoupdate

      - name: pre-commit run -a
        run: SKIP=dbt-compile,dbt-docs-generate uv run pre-commit run -a

      - uses: EndBug/add-and-commit@v9
        id: add-and-commit
        with:
            author_name: Github Actions
            author_email: actions@github.com
            new_branch: update/pre-commit-hooks-${{ github.run_id }}

      # To ensure the PR triggers CI workflows it needs to use someone's PAT instead of the default GITHUB_TOKEN
      - name: Create Pull Request
        if: steps.add-and-commit.outputs.committed == 'true'
        run: |
            export GITHUB_TOKEN= && \
            echo ${{ secrets.PAT_GITHUB }} > token.txt && \
            gh auth login --with-token < token.txt && \
            gh pr create -B stg -H update/pre-commit-hooks-${{ github.run_id }} --title 'Pre-commit hook update ${{ github.run_id }}' --body 'Created by Github action'
